### PR TITLE
Update WORLD

### PR DESCRIPTION
**Pull request by r9y9**
includes improvement: https://github.com/mmorise/World/pull/37

and bug fix: https://github.com/mmorise/World/issues/39

### CODE REVIEW

**Comment by r9y9** [comment]
By the way, I would like to have a package depends on this. Do you have a plan to release the package on PyPI? I believe this is the best maintained and tested package for the WORLD wrapper. I (and hopefully others) would be happy with this is available on PyPI, so that we can install it by simply `pip install pyworld`.

**Comment by JeremyCCHsu** [comment]
@r9y9 Sorry to let you down, but I don't know how to distribute `pyworld` to PyPI because `pyworld` depends on `WORLD` submodule. It's unclear to me how to ask publish `pyworld` with current dependency architecture.

Here's what I guess I should do:
1. create a branch that contains the `WORLD` code.
2. remove the `submodule`
3. publish the branch to PyPI.

The problem is that the user may not have the latest `WORLD`. I'm not sure if this is the right practice. 

Please share your wisdom with me if you know how to do this.
Thanks

**Comment by r9y9** [comment]
Thank you very much for taking care of release! As I doing in https://github.com/r9y9/pysptk, I think it should be enough to include WORLD sources into the source distribution (#11).

**Comment by JeremyCCHsu** [comment]
Hey, @r9y9, it is me who should say thank you. :)
I've published pyworld to PyPI, so now it's possible to do `pip install pyworld`.
(I'll update the readme file)

Thank you very much for your great help.
In addition, allow me to take this chance to thank you for the `pysptk` module which I also used a lot in our research. 👍

**Pull request merged**
