### PR TITLE
Add support for Python 3.7

### PR DESCRIPTION
**Pull request by tats-u**
Edited:
- README
- .travis.yml
- appveyor.yml

It may not work properly so far.
Blocked by: #29

### CODE REVIEW

**Comment by JeremyCCHsu** [comment]
Thank you so much, @tats-u !

**Comment by tats-u** [comment]
It's not been merged, and I rebased #29.

**Comment by JeremyCCHsu** [comment]
Ah, my bad. Why is Github preventing me from reopening this PR?

**Comment by tats-u** [comment]
I suppose that's because I pushed the rebased commit with force.

**Pull request closed without merging**
